version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-

      - run:
          name: Install
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Tests
          commands: yarn test

workflows:
    build-and-test:
      jobs:
        - build-and-test