version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:dubnium

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - dependencies-

      - run:
          name: Install
          command: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "package.json" }}

      - run:
          name: Lint
          command: yarn lint

      - run:
          name: Tests
          commands: yarn test
